version: '3.8'
services:
  web:
    build: ./packages/web
    volumes:
      - ./packages/web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./packages/server
    volumes:
      - ./packages/server:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: j49OPekq9PlKj
    ports:
      - "5433:5432"  #The internal PostgreSQL port is always
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "youn4ik@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123456"
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  node_modules:
